Repository EngineersBox/NewsAggregator, pull requests merged in 2021-10, with the labels that each got.

#13 Docker name
  compose/elasticsearch/Dockerfile
  compose/opensearch/Dockerfile
  compose/opensearch/docker-compose.yml
  compose/opensearch/opensearch.yml
Labels: deployment, elasticsearch

#19 UIUX 20 Configure OpenSearch for better ingestion
  compose/opensearch/docker-compose.yml
Labels: enhancement, elasticsearch

#31 UI ux 73 implement the autocomplete search
  app.py
Labels: enhancement, API

#32 :hammer: Fixed target repo URL
  ansible/site.yml
Labels: bug, deployment

#30 UIUX-74 New box deployment for caddy and frontend
  .github/listContains.sh
  .github/workflows/ansible.yml
  Dockerfile
  ansible/ansible.cfg
  ansible/inventory/old.ini
  ansible/inventory/prod.ini
  ansible/roles/backend/tasks/main.yml
  ansible/roles/frontend/tasks/main.yml
  ansible/roles/opensearch/tasks/main.yml
  ansible/site.yml
  caddy/Caddyfile
  caddy/Dockerfile
  compose/backend/docker-compose.yml
  compose/caddy/docker-compose.yml
  compose/frontend/docker-compose.yml
  compose/opensearch/docker-compose.yml
  compose/opensearch/opensearch.yml
  compose/redis/docker-compose.yml
  frontend_new/Dockerfile
Labels: enhancement, deployment

#37 UI ux 73 requirement document
  Dockerfile
  Makefile
  ansible/roles/opensearch/tasks/main.yml
  app.py
  knn_indexing/index.py
Labels: bug, API

#39 UIUX-73 Make wikidump accessible to Dockerfiles within repo directory
  Dockerfile
  ansible/site.yml
  app.py
  index_datas/import_datas.py
Labels: deployment, API, elasticsearch
